const sampleDesktopTableData = {
    totalPages: 10,
    totalDocuments: 10,
    data: [
        {
            id: 1,
            name: "Acme Corporation",
            address: "123 Acme St, Suite 400",
            country: "USA",
            state: "California",
            pincode: "90001",
            contact: "+1 555-1234",
            email: "contact@acme.com",
            status: "active",
            remarks: "Main office located in California.",
        },
        {
            id: 2,
            name: "Global Enterprises",
            address: "456 Global Rd, Building 5",
            country: "Canada",
            state: "Ontario",
            pincode: "M5G 2C3",
            contact: "+1 416-555-6789",
            email: "support@globalent.com",
            status: "active",
            remarks: "Global headquarters in Ontario, Canada.",
        },
        {
            id: 3,
            name: "Tech Innovators Inc.",
            address: "789 Innovation Dr, Tech Park",
            country: "UK",
            state: "London",
            pincode: "EC1A 1BB",
            contact: "+44 20 7946 0958",
            email: "info@techinnovators.com",
            status: "active",
            remarks: "A leading technology firm in London.",
        },
        {
            id: 4,
            name: "Green Energy Solutions",
            address: "101 Greenway Blvd, Green District",
            country: "Germany",
            state: "Berlin",
            pincode: "10115",
            contact: "+49 30 1234567",
            email: "contact@greenenergy.com",
            status: "active",
            remarks: "Sustainable energy solutions provider.",
        },
        {
            id: 5,
            name: "Retail Giant Group",
            address: "202 Mall St, Retail Plaza",
            country: "USA",
            state: "New York",
            pincode: "10001",
            contact: "+1 212-555-9876",
            email: "sales@retailgiant.com",
            status: "active",
            remarks: "Leading retail chain in North America.",
        },
        {
            id: 6,
            name: "Blue Ocean Technologies",
            address: "303 Ocean Ave, Blue Tech Building",
            country: "Australia",
            state: "New South Wales",
            pincode: "2000",
            contact: "+61 2 9876 5432",
            email: "support@blueocean.com",
            status: "active",
            remarks: "Focus on ocean technologies and research.",
        },
        {
            id: 7,
            name: "Apex Logistics",
            address: "404 Apex Rd, Logistics Hub",
            country: "India",
            state: "Maharashtra",
            pincode: "400001",
            contact: "+91 22 2345 6789",
            email: "logistics@apex.com",
            status: "active",
            remarks: "Efficient supply chain and logistics services.",
        },
        {
            id: 8,
            name: "Digital Creatives Studio",
            address: "505 Pixel Ln, Design Tower",
            country: "USA",
            state: "Texas",
            pincode: "73301",
            contact: "+1 512-555-1122",
            email: "info@digitalcreatives.com",
            status: "active",
            remarks: "Creative digital marketing and design studio.",
        },
        {
            id: 9,
            name: "Smart Solutions Pvt Ltd.",
            address: "606 Smart St, Techno Park",
            country: "Singapore",
            state: "Central",
            pincode: "018968",
            contact: "+65 1234 5678",
            email: "contact@smartsolutions.sg",
            status: "inactive",
            remarks: "Providing IT and business solutions across Asia.",
        },
        {
            id: 10,
            name: "Advanced Manufacturing Co.",
            address: "707 Industry Blvd, Factory Zone",
            country: "Japan",
            state: "Tokyo",
            pincode: "100-0001",
            contact: "+81 3 1234 5678",
            email: "contact@advancedmanufacturing.jp",
            status: "active",
            remarks: "Experts in advanced manufacturing and robotics.",
        },
    ],
};

export default sampleDesktopTableData;
