// GET DESKTOP MODULE
const BASE_ROUTE = "/api/v1/desktop";
// DESKTOP LIST
METHOD = "GET";
ROUTE = "/";
QUERY = {
    deviceStatus: "in_use",
    oem: "dell",
    ram: "8",
    limit: "10",
    page: "10",
    searchText: "search text...",
};
RESPONSE = {
    totalPages: 16,
    totalDocuments: 156,
    data: [
        {
            _id: "6486cae1284e1728606f902c",
            "Product Name": "Dell Latitude 5420",
            "Serial Number": "ABC123456789",
            "Service Tag": "XYZ987654321",
            OEM: "Dell",
            Model: "Latitude 5420",
            Processor: "Intel Core i7-1185G7",
            "Disk Space (GB)": 512,
            "RAM (GB)": 16,
            "CPU Core Count": 4,
            CPE: "cpe:2.3:h:dell:latitude_5420:-:*:*:*:*:*:*:*",
            "Device Status": "In Use",
            "Procurement Date": "2022-03-15",
            "Acquisition Date": "2022-03-20",
            "Warranty Expiry": "2025-03-15",
            "End of Support": "2027-03-15",
            "End of Life": "2030-03-15",
            "Procurement Period": "Q1 2022",
            "IP Address": "192.168.1.100",
            "IP Allocation Type": "Static",
            "MAC Address": "00:1A:2B:3C:4D:5E",
            "NIC Count": 2,
            "Assigned Date": "2022-03-25",
            "Asset ID": "ASSET12345",
            "Asset Location": "New York Office",
            "Operating System (with version)": "Windows 10 Pro 21H2",
            "AD User Name": "john.doe",
            "Responsible (Managed By)": "IT Department",
            "Custodian Name": "John Doe",
            "Custodian Email": "john.doe@example.com",
            "Custodian Department": "IT",
            "Business Impact": "High",
            "Antivirus Status": "Enabled",
            Vendor: "Dell Technologies",
            "Device Source": "Direct Purchase",
            "Bill Order Number": "BO123456",
            "Bill Order Date": "2022-03-10",
            "Store Item Number": "SI789012",
            "Capital Expenditure (CapEx)": 1200,
            "Operational Expenditure (OpEx)": 50,
            "Device State": "Active",
            "Last Audit Date (If Any)": "2023-09-01",
            "Patch Level": "Latest",
        },
        {
            _id: "6486cae1284e1728606f902d",
            "Product Name": "HP EliteBook 840 G8",
            "Serial Number": "DEF987654321",
            "Service Tag": "LMN123456789",
            OEM: "HP",
            Model: "EliteBook 840 G8",
            Processor: "Intel Core i5-1135G7",
            "Disk Space (GB)": 256,
            "RAM (GB)": 8,
            "CPU Core Count": 4,
            CPE: "cpe:2.3:h:hp:elitebook_840_g8:-:*:*:*:*:*:*:*",
            "Device Status": "In Storage",
            "Procurement Date": "2021-11-10",
            "Acquisition Date": "2021-11-15",
            "Warranty Expiry": "2024-11-10",
            "End of Support": "2026-11-10",
            "End of Life": "2029-11-10",
            "Procurement Period": "Q4 2021",
            "IP Address": "192.168.1.101",
            "IP Allocation Type": "DHCP",
            "MAC Address": "00:1B:2C:3D:4E:5F",
            "NIC Count": 1,
            "Assigned Date": "2021-11-20",
            "Asset ID": "ASSET67890",
            "Asset Location": "San Francisco Office",
            "Operating System (with version)": "Windows 11 Pro 22H2",
            "AD User Name": "jane.smith",
            "Responsible (Managed By)": "IT Department",
            "Custodian Name": "Jane Smith",
            "Custodian Email": "jane.smith@example.com",
            "Custodian Department": "Finance",
            "Business Impact": "Medium",
            "Antivirus Status": "Enabled",
            Vendor: "HP Inc.",
            "Device Source": "Reseller",
            "Bill Order Number": "BO654321",
            "Bill Order Date": "2021-11-05",
            "Store Item Number": "SI098765",
            "Capital Expenditure (CapEx)": 1000,
            "Operational Expenditure (OpEx)": 40,
            "Device State": "Inactive",
            "Last Audit Date (If Any)": "2023-08-15",
            "Patch Level": "Pending",
        },
        {
            _id: "6486cae1284e1728606f902e",
            "Product Name": "Lenovo ThinkPad X1 Carbon",
            "Serial Number": "GHI123456789",
            "Service Tag": "OPQ987654321",
            OEM: "Lenovo",
            Model: "ThinkPad X1 Carbon Gen 9",
            Processor: "Intel Core i7-1165G7",
            "Disk Space (GB)": 1024,
            "RAM (GB)": 32,
            "CPU Core Count": 4,
            CPE: "cpe:2.3:h:lenovo:thinkpad_x1_carbon_gen9:-:*:*:*:*:*:*:*",
            "Device Status": "In Use",
            "Procurement Date": "2023-01-10",
            "Acquisition Date": "2023-01-15",
            "Warranty Expiry": "2026-01-10",
            "End of Support": "2028-01-10",
            "End of Life": "2031-01-10",
            "Procurement Period": "Q1 2023",
            "IP Address": "192.168.1.102",
            "IP Allocation Type": "Static",
            "MAC Address": "00:1C:2D:3E:4F:5A",
            "NIC Count": 2,
            "Assigned Date": "2023-01-20",
            "Asset ID": "ASSET54321",
            "Asset Location": "Chicago Office",
            "Operating System (with version)": "Windows 11 Pro 22H2",
            "AD User Name": "alice.johnson",
            "Responsible (Managed By)": "IT Department",
            "Custodian Name": "Alice Johnson",
            "Custodian Email": "alice.johnson@example.com",
            "Custodian Department": "HR",
            "Business Impact": "High",
            "Antivirus Status": "Enabled",
            Vendor: "Lenovo",
            "Device Source": "Direct Purchase",
            "Bill Order Number": "BO987654",
            "Bill Order Date": "2023-01-05",
            "Store Item Number": "SI123456",
            "Capital Expenditure (CapEx)": 1500,
            "Operational Expenditure (OpEx)": 60,
            "Device State": "Active",
            "Last Audit Date (If Any)": "2023-09-10",
            "Patch Level": "Latest",
        },
        {
            _id: "6486cae1284e1728606f902f",
            "Product Name": "Apple MacBook Pro 16",
            "Serial Number": "JKL123456789",
            "Service Tag": "RST987654321",
            OEM: "Apple",
            Model: "MacBook Pro 16 (M1 Pro)",
            Processor: "Apple M1 Pro",
            "Disk Space (GB)": 512,
            "RAM (GB)": 16,
            "CPU Core Count": 10,
            CPE: "cpe:2.3:h:apple:macbook_pro_16_m1_pro:-:*:*:*:*:*:*:*",
            "Device Status": "In Use",
            "Procurement Date": "2022-09-05",
            "Acquisition Date": "2022-09-10",
            "Warranty Expiry": "2025-09-05",
            "End of Support": "2027-09-05",
            "End of Life": "2030-09-05",
            "Procurement Period": "Q3 2022",
            "IP Address": "192.168.1.103",
            "IP Allocation Type": "Static",
            "MAC Address": "00:1D:2E:3F:4A:5B",
            "NIC Count": 2,
            "Assigned Date": "2022-09-15",
            "Asset ID": "ASSET67891",
            "Asset Location": "Austin Office",
            "Operating System (with version)": "macOS Ventura 13.0",
            "AD User Name": "bob.wilson",
            "Responsible (Managed By)": "IT Department",
            "Custodian Name": "Bob Wilson",
            "Custodian Email": "bob.wilson@example.com",
            "Custodian Department": "Marketing",
            "Business Impact": "High",
            "Antivirus Status": "Enabled",
            Vendor: "Apple Inc.",
            "Device Source": "Direct Purchase",
            "Bill Order Number": "BO456789",
            "Bill Order Date": "2022-09-01",
            "Store Item Number": "SI654321",
            "Capital Expenditure (CapEx)": 2500,
            "Operational Expenditure (OpEx)": 70,
            "Device State": "Active",
            "Last Audit Date (If Any)": "2023-09-05",
            "Patch Level": "Latest",
        },
    ],
};
